### PR TITLE
Configuration for docker and dependency fixes

### PR DESCRIPTION
**Pull request by UO281801**
Edited the docker-compose.yml file for MariaDB and file restapi/src/db/persistence MySQL.ts to use the database in Docker. Fixed dependencies' problems in Webapp (star rating component was removed and will be replaced by a better alternative to avoid peer-dependency problems). Removed also unused imports and majority of warnings.
There is one error in the docker-compose still: the restapi does not wait for the database to be fully built, so it causes a "connection refused" error in the first execution

### CODE REVIEW

**Review by PabVF23 — APPROVED** [review]
The modifications seem to be working as intended. I approve this merge.

**Comment by UO281801** [comment]
The star rating component was corrected

**Comment by Diego-274** [comment]
The changes seem correct. I am okay with the merge,

**Review by Diego-274 — APPROVED** [review]

**Comment by UO282497** [comment]
Deployment works fine on my PC, and there were no errors with any dependencies.

**Pull request merged**
